feature: WEOS-1365 As a developer I should be able set an example to be returned if there is no controller set
wepala/weos pull request #124
Opened 2022-02-25 16:12 UTC by shaniah868

* **Please check if the PR fulfills these requirements**
- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

* **Other information**:

2022-03-01 10:39 UTC, akeemphilbert requested changes

2022-03-01 10:39 UTC, akeemphilbert commented on controllers/rest/controller_standard.go
> +				if found {
why is this needed here? It looks like lower in the code if you find something you already break?

2022-03-01 10:39 UTC, akeemphilbert commented on controllers/rest/controller_standard.go
> +				if resp.Value.Content != nil {
Sending this header is optional. I think the code here should be written in a way that it only tries to loop through and find a matching type IF the Accept header is passed in AND there are multiple responses. If there is not response that matches the Accept header you should server the first one (Accept header is a HINT not a requirement https://developer.mozilla.org/en-US/docs/Web/HTTP/Content_negotiation)

2022-03-02 15:45 UTC, Aidan-E submitted a review, later dismissed

2022-03-02 18:20 UTC, Aidan-E submitted a review, later dismissed

2022-03-02 18:24 UTC, akeemphilbert approved these changes, later dismissed

2022-03-02 19:33 UTC, akeemphilbert approved these changes

2022-03-02 19:34 UTC, merged