Feature/weos 1295 - As a developer I should be able to associate a html page to a html response
wepala/weos pull request #136
Opened 2022-03-08 17:35 UTC by RandyDeo

* **Please check if the PR fulfills these requirements**
- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

* **Other information**:

2022-03-09 15:46 UTC, Aidan-E submitted a review, later dismissed

2022-03-09 18:14 UTC, akeemphilbert requested changes

2022-03-09 18:14 UTC, akeemphilbert commented on controllers/rest/api_test.go
> +          x-file: "../../staticF/index"
reference a folder in the fixtures folder (where all other fixtures are)

2022-03-09 18:14 UTC, akeemphilbert commented on controllers/rest/operation_initializers.go
> +	for _, resp := range operation.Responses {
move this to the RouteInitializer because essentially api.e.File is setting up a route

2022-03-09 18:14 UTC, akeemphilbert commented on staticF/index
> +<html><head><title>Test Page</title></head><body>Test Page</body></html>
this should really be in some fixtures folder

2022-03-11 12:13 UTC, akeemphilbert requested changes

2022-03-11 12:13 UTC, akeemphilbert commented on controllers/rest/operation_initializers.go
> +		if middleware, _ := api.GetMiddleware("DefaultResponseMiddleware"); middleware != nil {
So this being a middleware might be a good thing (I was initially thinking it wasn't). You can in theory pair this middleware with the other standard middleware and have the "Default" controller attached in all instances (and stop using the other standard controllers)

2022-03-12 10:47 UTC, akeemphilbert requested changes
Functionally it seems fine

2022-03-12 10:47 UTC, akeemphilbert commented on context/context.go
> +const BASIC_RESPONSE string = "basic_response"
prefix with an underscore to avoid collisions

2022-03-12 10:47 UTC, akeemphilbert commented on controllers/rest/controller_standard.go
>  			if activatedResponse["example"] == true {
why isn't this simply declared as a boolean on 675?

2022-03-14 16:28 UTC, Aidan-E approved these changes

2022-03-14 18:44 UTC, akeemphilbert approved these changes

2022-03-14 18:44 UTC, merged