feature: WEOS-1382 As a developer I should be able to set the type of id that I want auto generated
wepala/weos pull request #140
Opened 2022-03-09 19:26 UTC by shaniah868

* **Please check if the PR fulfills these requirements**
- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

-Now you can auto generate your x-identifier once only one is specified based on its format
-If the format is not specified and error is thrown

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

* **Other information**:

2022-03-10 18:47 UTC, Aidan-E submitted a review, later dismissed

2022-03-11 11:47 UTC, akeemphilbert requested changes
When I removed "And" from one of the steps so that is uses the same "the specification is" as the other features, the tests failed

2022-03-11 11:47 UTC, akeemphilbert commented on model/content_entity.go
> +	schema := entityFactory.Schema()
why are you passing in the EntityFactory? the schema is already on the object (FromSchemaAndBuilder)

2022-03-11 11:47 UTC, akeemphilbert commented on model/content_entity.go
> +	properties := entityFactory.Schema().ExtensionProps.Extensions["x-identifier"]
though passing in the schema is not needed, you set a variable "schema" then you still use the schema on the entity factory?

2022-03-11 11:47 UTC, akeemphilbert commented on model/content_entity.go
> +func GenerateID(payload []byte, entityFactory EntityFactory) ([]byte, error) {
This should be a function ON a content entity that is maybe triggered on an isValid call. The isvalid could check to see if the identifier fields have value and if the identifier is one field then trigger the generateID function

2022-03-11 11:47 UTC, akeemphilbert commented on model/receiver.go
> +	payload, err = GenerateID(payload, entityFactory)
this should have been instantiating the ContentEntity with the payload (maybe we need a construction FromSchemaAndBuilderAndPayload)

2022-03-14 21:29 UTC, akeemphilbert approved these changes

2022-03-15 18:54 UTC, Aidan-E approved these changes

2022-03-16 10:17 UTC, merged