Feature/weos 1378
wepala/weos pull request #150
Opened 2022-03-21 19:05 UTC by RandyDeo

* **Please check if the PR fulfills these requirements**
- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

* **Other information**:

2022-03-23 16:47 UTC, Aidan-E approved these changes

2022-03-23 17:22 UTC, Aidan-E requested changes
Static file issue encountered.

2022-03-28 15:53 UTC, Aidan-E submitted a review, later dismissed
Static file issue resolved✅

2022-03-29 07:33 UTC, akeemphilbert requested changes

2022-03-29 07:33 UTC, akeemphilbert commented on controllers/rest/fixtures/kollectables-api.yaml
> +openapi: 3.0.3
I wouldn't want this here as it contains details of another project

2022-03-31 11:15 UTC, akeemphilbert approved these changes

2022-03-31 11:15 UTC, merged