Feature/weos 1130
wepala/weos pull request #30
Opened 2022-01-11 18:16 UTC by RandyDeo

* **Please check if the PR fulfills these requirements**
- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

* **Other information**:

2022-01-12 15:34 UTC, akeemphilbert requested changes

2022-01-12 15:34 UTC, akeemphilbert commented on controllers/rest/controller_standard.go
> +				result, err := projection.GetContentEntity(weosID, contentType)
I think GetContentEntity could return a struct that we define since we know all items have weosID, and sequence no. on them. There already is a ContentEntity in the model in theory the FromSchemaWithValues constructor could be used. iF you do this then the NewEtag could use ContentEntity instead

2022-01-12 15:34 UTC, akeemphilbert commented on controllers/rest/api_test.go
> +		{ID: "1", Title: "Blog 1", Url: "www.testBlog1.com"},
Use non numeric ids to be sure that this is not a false postiive

2022-01-12 15:34 UTC, akeemphilbert commented on controllers/rest/utils.go
> +func NewEtag(weosID string, seqNo int64) string {
If switching to using strongly typed ContentType then make NewEtag take contenttype as an argument

2022-01-12 15:34 UTC, akeemphilbert commented on features/define-create-endpoint-oas.feature
> +@skipped
This should not be

2022-01-12 15:34 UTC, akeemphilbert commented on features/define-content-type-oas.feature
> +@skipped
this should not be here

2022-01-12 15:34 UTC, akeemphilbert commented on projections/gorm.go
> +func (p *GORMProjection) GetContentEntity(weosID, contentType string) (map[string]interface{}, error) {
Update this to return model.ContentEntity

2022-01-13 00:12 UTC, akeemphilbert approved these changes

2022-01-13 14:02 UTC, Aidan-E approved these changes
Blog created with e-tag displayed.

2022-01-13 15:35 UTC, merged