Feature/weos 1124
wepala/weos pull request #38
Opened 2022-01-13 15:38 UTC by RandyDeo

* **Please check if the PR fulfills these requirements**
- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

* **Other information**:

2022-01-13 15:49 UTC, Aidan-E submitted a review, later dismissed
Blog created successfully with all parameters fulfilled.

2022-01-13 16:30 UTC, akeemphilbert requested changes

2022-01-13 16:30 UTC, akeemphilbert commented on features/create-content.feature
> +@skipped
This should not be skipped I believe

2022-01-13 16:30 UTC, akeemphilbert commented on end2end_test.go
> +			case "Null":
remove the commented out code

2022-01-13 17:54 UTC, akeemphilbert approved these changes

2022-01-13 17:59 UTC, akeemphilbert requested changes

2022-01-13 17:59 UTC, akeemphilbert commented on end2end_test.go
> +
Null check works for mysql and postgres just not sqlite. Make an exception only for sqlite

2022-01-17 13:55 UTC, akeemphilbert requested changes

2022-01-17 13:55 UTC, akeemphilbert commented on projections/projections_test.go
> +			case "mysql":
check for not sqlite

2022-01-17 14:08 UTC, akeemphilbert approved these changes

2022-01-17 14:08 UTC, merged