Feature/weos 1176
wepala/weos pull request #43
Opened 2022-01-14 17:02 UTC by shaniah868

* **Please check if the PR fulfills these requirements**
- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

* **Other information**:

2022-01-14 17:36 UTC, Aidan-E submitted a review, later dismissed
Blog created and listing function worked successfully.

2022-01-17 14:03 UTC, akeemphilbert requested changes

2022-01-17 14:03 UTC, akeemphilbert commented on controllers/rest/api.go
> +									if val.Schema.Value.Properties != nil && val.Schema.Value.Properties["items"] != nil && val.Schema.Value.Properties["items"].Value.Type == "array" && val.Schema.Value.Properties["items"].Val
this should also check for extension `x-alias` items

2022-01-17 18:39 UTC, akeemphilbert approved these changes

2022-01-17 18:40 UTC, merged