Feature/weos 1132 - As a developer I should be able to update an item for a content type
wepala/weos pull request #55
Opened 2022-01-21 17:40 UTC by atoniaw

* **Please check if the PR fulfills these requirements**
- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

- Allows users to edit a specific item in the database
- Allows users to see a specific item in the datatabase (WEOS-1135)

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

- Foreign keys changed to pointers to account for empty foreign keys in payload.  The database would not allow for item creation otherwise if the foreign key defaults to a blank string instead of null.  This may cause existing databases to become unusable.  

* **Other information**:

2022-01-24 16:03 UTC, Aidan-E submitted a review, later dismissed
Passed all parameters of functional review.

2022-01-25 09:44 UTC, akeemphilbert requested changes

2022-01-25 09:44 UTC, akeemphilbert commented on controllers/rest/utils.go
> +func GetContentBySequenceNumber(eventRepository model.EventRepository, id string, sequence_no int64) (*model.ContentEntity, error) {
This should be in the model package not the controller

2022-01-25 09:44 UTC, akeemphilbert commented on model/utils.go
> +func GetSeqfromPayload(payload []byte) (string, error) {
Why do we need to get the sequence no. from the payload? shouldn't it either be on the entity or command? If this is getting the sequence no. from a projection then this should be in the projection package

2022-01-26 09:27 UTC, akeemphilbert submitted a review, later dismissed

2022-01-26 15:03 UTC, Aidan-E submitted a review, later dismissed

2022-01-26 16:21 UTC, akeemphilbert submitted a review, later dismissed

2022-01-26 19:07 UTC, akeemphilbert submitted a review, later dismissed

2022-01-27 10:02 UTC, akeemphilbert approved these changes

2022-01-27 10:02 UTC, merged