Feature/weos 1289 - As a developer I should be able to specify that an endpoint request body is form data
wepala/weos pull request #64
Opened 2022-01-26 16:35 UTC by RandyDeo

* **Please check if the PR fulfills these requirements**
- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

* **Other information**:

2022-01-26 18:46 UTC, Aidan-E submitted a review, later dismissed

2022-01-27 10:14 UTC, akeemphilbert requested changes
There are few relevant scenarios that are skipped

2022-01-27 10:14 UTC, akeemphilbert commented on controllers/rest/controller_standard.go
> +		//payload, _ := ioutil.ReadAll(ctxt.Request().Body)
if this is no longer needed please remove

2022-01-27 10:14 UTC, akeemphilbert commented on features/create-content.feature
> +    @WEOS-1289 @skipped
this is still being skipped

2022-01-27 10:14 UTC, akeemphilbert commented on features/create-content.feature
> +    @WEOS-1289 @skipped
this is still being skipped

2022-01-27 23:39 UTC, akeemphilbert approved these changes

2022-01-28 00:07 UTC, merged