Feature/weos 1125
wepala/weos pull request #86
Opened 2022-02-08 14:41 UTC by atoniaw

* **Please check if the PR fulfills these requirements**
- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

* **Other information**:

2022-02-08 20:09 UTC, akeemphilbert requested changes
Remove tests.db and tasks.db and update gitignore

2022-02-08 20:09 UTC, akeemphilbert commented on controllers/rest/middleware_initialize.go
> +	dfs, _ := json.Marshal(ref.Extensions["x-remove"])
please use constants to reference the extension names so that if we decide to rename in the future it would be an update in one place

2022-02-08 20:09 UTC, akeemphilbert commented on projections/gorm.go
> +func (p *GORMProjection) Migrate(ctx context.Context, builders map[string]ds.Builder, refs map[string]*openapi3.SchemaRef) error {
it would be clearer to have a property that was a map of the table name and fields to remove that pass the schema ref.

2022-02-08 20:09 UTC, akeemphilbert commented on projections/gorm.go
> +				db := p.db.Debug().Table(entityFactory.Name()).Create(eventPayload)
remove debug call

2022-02-09 14:39 UTC, Aidan-E requested changes
"id" field is not displayed when creating a blog.

2022-02-11 09:07 UTC, akeemphilbert approved these changes, later dismissed

2022-02-14 14:38 UTC, akeemphilbert approved these changes, later dismissed

2022-02-14 17:52 UTC, Aidan-E approved these changes, later dismissed

2022-02-14 19:46 UTC, akeemphilbert approved these changes

2022-02-14 19:47 UTC, merged